image: docker:stable

stages:
  - build
  - tests

nginx:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH'
      changes:
        - deployment/gitlab/nginx/*
      when: on_success
    - if: '$CI_COMMIT_MESSAGE =~ /\[ci buildNginx\]/i || $BUILD_NGINX'
      when: always
  script:
    - docker build . -f ./deployment/gitlab/nginx/Dockerfile

app:
  stage: build
  only:
    - branches
  script:
    - docker build . -f deployment/gitlab/php/Dockerfile

phpunit:
  stage: tests
  only:
    - branches
  services:
    - postgres:9.6.16-alpine
  script:
    - rm -rf ./vendor
    - docker build . -f deployment/gitlab/php/Dockerfile -t app_test_image
    - docker run -v $(pwd):/var/www app_test_image bash -c "cd /var/www/ && cp .env.example /var/www/.env && composer install && php artisan key:generate && php artisan migrate:fresh --database=pgsql --seed && php -d xdebug.remote_enable=0 vendor/phpunit/phpunit/phpunit && rm -rf /vendor"
#    - docker run app_test_image bash -c "php -d xdebug.remote_enable=0 vendor/phpunit/phpunit/phpunit"
#      cp .env.example /var/www/.env;
#      cd /var/www;
#      ./artisan key:generate;
#      ./artisan migrate:fresh --database=app_db --seed;
#      php -d xdebug.remote_enable=0 vendor/phpunit/phpunit/phpunit
  variables:
    POSTGRES_DB: app_db
    POSTGRES_USER: app_db
    POSTGRES_PASSWORD: ""
    POSTGRES_HOST_AUTH_METHOD: "trust"
