version: '3'
services:

  app:
    build:
      context: deployment/local/php
    working_dir: /var/www
    depends_on:
      - db
    environment:
      - PHP_ENABLE_XDEBUG
    volumes:
      - ./:/var/www
      - ~/.composer-docker/cache:/root/.composer/cache
      - ./deployment/local/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./deployment/local/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint

  web:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 8580:443
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./deployment/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./deployment/local/nginx/ssl:/etc/nginx/ssl

  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_db
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 8581:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  node:
    image: node:14.3-alpine
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
