apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: public-files
          emptyDir: {}
      containers:
        - name: nginx
          imagePullPolicy: Always
          #image: $(minikube ip):5000/nginx:base
          image: 192.168.49.2:5000/nginx:base
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
          volumeMounts:
            - name: public-files
              mountPath: /var/www/html
        - name: app
          imagePullPolicy: Always
          image: 192.168.49.2:5000/app:base
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    rsync -av /var/www/. /var/www/html --exclude /var/www/html;
                    cd /var/www/html;
                    artisan optimize;
          ports:
            - containerPort: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
          volumeMounts:
            - name: public-files
              mountPath: /var/www/html
          env:
            - name: APP_KEY
              value: "base64:TIUStF7JhiZTIHrbxnEiQZ/IBDxkYsoQTdkHMhVUjsQ="
            - name: LOG_CHANNEL
              value: "stderr"
            - name: APP_BASE_PATH
              value: "/var/www/html"
